name: Build and Publish to itch.io

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GODOT_VERSION: 4.6
      ITCH_USER: 2bytesgoat
      ITCH_GAME: dragon-jump

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Inject runtime secrets
        run: |
          cat > src/scripts/singletons/runtime_secrets.gd <<EOF
          extends Node
          const is_set = true
          const SILENT_WOLF_API_KEY = "${{ secrets.SILENT_WOLF_API_KEY }}"
          const SILENT_WOLF_GAME_ID = "${{ secrets.SILENT_WOLF_GAME_ID }}"
          EOF

      - name: Download Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          mv Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot
          chmod +x godot

      - name: Download export templates
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz

          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

          unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export game (Web)
        run: |
          mkdir -p build/web
          ./godot --headless --export-release "Web" build/web/index.html --encryption-key ${{ secrets.GODOT_PCK_ENCRYPTION_KEY }}

      - name: Export game (Windows)
        run: |
          mkdir -p build/windows
          ./godot --headless --export-release "Windows Desktop" build/windows/${{ secrets.EXPORT_NAME }}.exe --encryption-key ${{ secrets.GODOT_PCK_ENCRYPTION_KEY }}

      - name: Download butler
        run: |
          wget https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default -O butler.zip
          unzip butler.zip
          chmod +x butler

      - name: Push Web to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY  }}
        run: |
          ./butler push build/web \
            $ITCH_USER/$ITCH_GAME:web

      - name: Push Windows to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY  }}
        run: |
          ./butler push build/windows \
            $ITCH_USER/$ITCH_GAME:windows
